os: osx
language: objective-c
osx_image: xcode9
xcode_workspace: cocoadialog.xcworkspace
xcode_sdk: macosx10.13

before_install:
  - brew update

install:
  - brew outdated xctool || brew upgrade xctool
  - brew upgrade node 2>/dev/null || brew install node
  - brew upgrade yarn 2>/dev/null || brew install yarn
  - yarn
  - /usr/local/bin/node -v
  - node -v
  - /usr/bin/env node -v
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet

script:
  - ./Scripts/build

after_success:
  - bash <(curl -s https://codecov.io/bash) -J '^cocoadialog$'
  - node ./Scripts/success

notifications:
  slack:
    secure: G5I3v9A1PtH3pb2l4zE9fip3KsuToVt0UGl2tQ4H6MEdA3RN0ioHOkEXG/t7clM+zvcKd2yugTYZYySVYjo8YYOc90s5BpJGpJ4ASgp1xwnd/iQgtKhuouRSDib2Ys5LwB0lL8Qds+FcD33OHrQNH06VD5T3dwhlidTjUPONtxQ=
